### ISSUE TITLE
invalid dim

### ISSUE THREAD

**Issue by Jackfrost2011** [nineteendo/ti84programs#2]
i had most of the code working before, but i had to fix a few mistakes i made, and now it says"invalid dim. i click goto, and it brings me to this. this is on a ti83. i used the ti83 code. this is for tetris
                 1→[A](A,B              
                 1→[A](A+D,B+E     <-- right here.
                 1→[A](A+F,B+G
                 1→[A](A+H,B+I

**Comment by nineteendo** [comment]
Have you compared with the code on GitHub? https://github.com/nineteendo/ti84programs/blob/master/tetris-84/tetris-84.md#variation-a---tetris-83

**Comment by Jackfrost2011** [comment]
yea, i copyed that code

**Comment by nineteendo** [comment]
There's going to be a mistake in your code somewhere. Either you check it yourself or you send me a video where you show the code of your program. Activate a-lock (2nd + alpha) and press down every 2 seconds.

**Comment by Jackfrost2011** [comment]
ill send you a video, but it will have to be twomarrow. i'm in 7th hour and am about to leave. ill make sure to like and subscribe on your video though! thanks!

**Comment by Jackfrost2011** [comment]
i will have to send it in portions cuz it cant be over 10 MB. also, please turn off the sound. my only explination is.... 7th grade.

**Comment by nineteendo** [comment]
You can send a Google drive link.

**Comment by Jackfrost2011** [comment]
ok

**Comment by Jackfrost2011** [comment]
about to send. i fixed the code so of corse now i have a different problem.

**Comment by Jackfrost2011** [comment]
also, i split the code into two different programs

**Comment by Jackfrost2011** [comment]
here you go (https://docs.google.com/presentation/d/1YeBaoXniu62Xap4dvkubo5Z_So4PpRgC9qO6CDG4d2w/edit?usp=sharing)

**Comment by Jackfrost2011** [comment]
your video and code were really helpfull. would you be able to make a code like this for a ti83 port of doom?

**Comment by nineteendo** [comment]
Probably not, but I've been working on a new version of Tetris and Pacman. By the way, you'll need to grant me access to view the video's.

**Comment by Jackfrost2011** [comment]
just did.

**Comment by Jackfrost2011** [comment]
i wont be online for another 2 hours or so

**Comment by nineteendo** [comment]
As far as I can see with the poor video quality, these lines are incorrect:

https://github.com/nineteendo/ti84programs/blob/da1669e2ddb8a48e35a31bcb8cdb57ec53da86a3/tetris-84/tetris-84.md?plain=1#L342

https://github.com/nineteendo/ti84programs/blob/da1669e2ddb8a48e35a31bcb8cdb57ec53da86a3/tetris-84/tetris-84.md?plain=1#L409

https://github.com/nineteendo/ti84programs/blob/da1669e2ddb8a48e35a31bcb8cdb57ec53da86a3/tetris-84/tetris-84.md?plain=1#L439

https://github.com/nineteendo/ti84programs/blob/da1669e2ddb8a48e35a31bcb8cdb57ec53da86a3/tetris-84/tetris-84.md?plain=1#L535-L537

I don't think you can split up the programs though. (At least not in the way you're doing it here).

Go to the "TETRIS" program, clear the `prgmATETRIS` line and then click <kbd>2ND</kbd>, <kbd>STO\></kbd>, <kbd>PRGM</kbd>, <kbd>LEFT</kbd>, select `ATETRIS` and press <kbd>ENTER</kbd>. Finally delete the `prgmATETRIS` line.
