### ISSUE TITLE
game over.

### ISSUE THREAD

**Issue by Jackfrost2011** [nineteendo/ti84programs#4]
i sent a video to your email

**Comment by Jackfrost2011** [comment]
it says invalid dim. could you give me all the parts that could effect that?
                1→[A](A,B  <---
                1→[A](A+D,B+E
                1→[A](A+F,B+G
                1→[A](A+H,B+I
                DelVar GIf B<M

**Comment by nineteendo** [comment]
Did you send me a new video? I haven't received anything.

**Comment by Jackfrost2011** [comment]
yea in sent it to this email:[nineteendo19d0@gmail.com]

**Comment by nineteendo** [comment]
Could you send it again?

**Comment by Jackfrost2011** [comment]
https://github.com/nineteendo/ti84programs/assets/146883259/752927d4-8480-4527-b955-5d65db98b4f8

**Comment by nineteendo** [comment]
Did you follow the ZOOM tutorial? https://youtu.be/9hnb9wAqQtc Then the graphics won't be messed up.

**Comment by Jackfrost2011** [comment]
no, i didnt realize i needed to. ill do that!

**Comment by nineteendo** [comment]
You'll have to send a new video of your program though. (After you've made the changes from here: #2).
And try to set the your phone (or camera) to the highest resolution when filming.
