### ISSUE TITLE
How to get new line between two lines of code

### ISSUE THREAD

**Issue by MrBunnyBunn** [nineteendo/ti84programs#5]
So I missed one line of code and if I push enter it doesn't creat a new line it just goes to the next line I was just wondering because I really do not want to restart

**Comment by nineteendo** [comment]
<kbd>2nd</kbd> + <kbd>Del (Ins)</kbd> + <kbd>Enter</kbd>

**Comment by MrBunnyBunn** [comment]
> 2nd + Del (Ins) + Enter

thank you so much
