### ISSUE TITLE
PACMAN issue

### ISSUE THREAD

**Issue by TheOof-lord** [nineteendo/ti84programs#6]
I just coded PACFIND on my TI-84 Plus SE. The game loads up just fine, and when I start the game, everything is find. However, the MOMENT the map is done loading, I get a SYNTAX error at line 22 (the line that reads Text(57,82,sub(">>>---",I,3). What could t he problem be? TY in advance!

**Comment by nineteendo** [comment]
Can you send a foto?

**Comment by TheOof-lord** [comment]
a photo of my code? sorry, i don't have a smart phone/ a way to take pictures and my only webcam p much never works. Is there any other way I could show you the code?
OH and also since I'm using an older version of the Ti-84 plus SE, there's no remainder function, so on line 63 (the one that reads 2+remainder(72+M,74→D), I used 2 + fPart(72+M,74→D)*(74->D). is that why I'm getting the error? if so, what change do I make to this part of the code?

**Comment by nineteendo** [comment]
Well, if you can't show me your code, I can show you how it's supposed to look:

<img src="https://github.com/user-attachments/assets/4bc29f6f-0c9d-423f-ad02-e856567d2e6e" alt="Screenshot_20241116-173846" width="400"/>

If you have a USB-B cable you could just transfer the program from your PC.

**Comment by TheOof-lord** [comment]
Sorry for the late reply, But I found the problem! I forgot to add a
parentheses to a part that needed one, LOL! However, I get a DOMAIN error
at line 52 (the one that reads If pxl-Test(C,4M-3D+2). The calculator takes
me to the end of that line. I have compared my code on this line to the
GITHUB version, and they are EXACTLY the same. What could be the problem
here? Again, thank you in advance!

**Comment by nineteendo** [comment]
It's probably not on that line, this means one of the variables has an invalid value. But, if you can't send me a screenshot or video of your code, I can't really help you. A single typo in the program is enough to break something. And I can't predict where it will be.

I can list some common pitfalls though:

- Use a `(-)` instead of `-` before numbers.
- Don't forget the trailing space on lines 54 and 58.

The `.txt` files are generated from the `.8xp` files and don't have comments to explain things.

**Comment by TheOof-lord** [comment]
Well, all of my unarchived programs were randomly deleted anyway, so it
I'll just reprogram that and ZOOM. Thank  you though!

**Comment by nineteendo** [comment]
Make sure to backup your programs using groups. It would be a shame if you lost them again. I'll close this, but you can re-open it you made a mistake again. Not sure how I will be able to help you though, maybe borrow a camera?
